data:
  source_path: "project/data/EURAUD_test.csv"
  news_path: "project/data/news_test.csv"

model:
  save_path: "project/models/test/"
  criterion: "accuracy"

backtest:
  initial_balance: 10000
  symbol: "EURAUD"
  max_trades: 50   # จำกัดจำนวน trade เพื่อให้ test รันเร็ว